### PR TITLE
BigTiff version

### PR DESCRIPTION
**Pull request by Milster**
The current implementation of BigTiff.

### CODE REVIEW

**Comment by Bobrovsky** [comment]
Thank you for the request but unfortunately it requires some changes before it can be merged.

The Main obstacle is: your version *always* produces BigTIFF files. I.e. any existing code depending on the library will break. 

Please also note that public methods should have XML Documentation Comments. And the code can not use any C# / .NET features not available in NET 2.0.

**Comment by Milster** [comment]
Our version only produces BigTIFF files if the "8"-flag is set or the offset exceeds the uint32-limit. We were able to write normal tiff files and read the with the old version in our tests. Could you explain in more detail which problems occur?

All the missing comments have been added now.

We also hope to have removed all features that are not part of the NET 2.0 standard.

**Comment by Bobrovsky** [comment]
Thank you for the improvements but there are some more issues left.

Please note that code can not be built if `FIX_JPEG_IS_OJPEG` is defined for the project. It's defined by default.

Most other issues can be reproduced by running unit tests provided with the library. 

For example, the code fails to read zackthecat.tif from the test case (see TestReadTileOJpeg test). The library outputs the following errors

`fetchDirectory: ..\..\..\TestCase\zackthecat.tif: Can not read TIFF directory count`
`ReadDirectory: ..\..\..\TestCase\zackthecat.tif: Failed to read directory at offset 0`

If you step into the code you will see that the code tries to read directory at 30425548324864 offset.

Also, at least some of the images produced by code of existing tests are bigger (byte wise) than before. And it looks like they have different offset to the first directory. It's not an error in itself but might be an indicator of an issue.

**Comment by Milster** [comment]
We've fixed the issue with wrong counts and offsets in case when SWAB-methods were used. We are now able to run all tests successfully.

The size check is misleading, as we need those 8 extra bytes as a buffer, in case a file has to be transformed from normal tiff to bigtiff when there is already some content written. Those 8 bytes don't produce any problem in runtime but will cause the majority of the tests to fail.

**Comment by Bobrovsky** [comment]
Thank you! I have merged your changes.

**Comment by simonmueller2** [comment]
Greate to see someone else is interested in bigtiff support. But is this feature working? I was not able to load any bigtiff data with the current version. 
Sample data http://www.awaresystems.be/imaging/tiff/bigtiff.html#samples

**Comment by Milster** [comment]
Could you please try to explain in further detail what you mean with "I was not able to load any bigtiff data". 

I was able to open all files, read their fields (at least those that were set) and was able to read the scanlines and copy them to a new file. If possible give a list of errors thrown and/or the difference between the expected and actual results.

Thank you.

**Comment by simonmueller2** [comment]
I had issues with the latest nuget version (2.4.518). When I use your version (https://github.com/Milster/libtiff.net) I do not have any problems! Thanks.

**Comment by Bobrovsky** [comment]
@Milster Did you improve your version of the library since the time I merged your pull request?
If you do then please post another pull request for the improvements. I will be happy to merge it.

**Comment by Milster** [comment]
@Bobrovsky  No, my version hasn't changed since the last merge. Could it be that the nuget version is somehow outdated?

**Comment by Bobrovsky** [comment]
@Milster Thank you, I've updated the NuGet version.

**Pull request merged**
