### PR TITLE
Added netstandard2.0 target

### PR DESCRIPTION
**Pull request by xfischer**
For netstandard2.0 projects referencing the library, a lot of netstandard1.3 libraries were needed

### CODE REVIEW

**Comment by Bobrovsky** [comment]
Thank you!

**Comment by xfischer** [comment]
You're welcome :) Can you push a new NuGet.

Thanks for this very very  useful library @Bobrovsky !

**Comment by Bobrovsky** [comment]
The new NuGet is already pushed.

**Comment by xfischer** [comment]
Sorry I didn’t Notice. Thanks !

**Pull request merged**
